### ISSUE TITLE
Delete phase ใช้ Patch (?)

### ISSUE THREAD

**Issue by pangpondwee** [IWING-IoT/iwing-iot-backend#2]
<img width="1512" alt="Screenshot 2024-01-04 at 4 43 09 PM" src="https://github.com/IWING-IoT/iwing-iot-backend/assets/73571113/c83a3f0b-653d-4db2-b805-f8c20ac76dbb">

**Comment by peeranat45** [comment]
เปลี่ยนเป้น DELETE /api/phase/:phaseId

**Comment by pangpondwee** [comment]
<img width="493" alt="Screenshot 2024-01-04 at 8 40 09 PM" src="https://github.com/IWING-IoT/iwing-iot-backend/assets/73571113/6938891f-3feb-4407-99f0-a947e42d01ba">
